name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-encryption-key: ${{ secrets.gradlekey }}
        dependency-graph: generate-and-submit
    - name: Gradle test and build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew build --configuration-cache


permissions:
  contents: write
  id-token: write